Stymied by not being able to have a pointer to a derived type with a coarray inside
```
../build/../objects/output_interface.f90:13:38:

       type(variable_t), pointer :: ptr
                                      1
Error: Component ‘ptr’ at (1) with coarray component shall be a nonpointer, nonallocatable scalar
```
was trying to use pointers to variables to store a dynamic list of variables to be output.  But variables contain a coarray
because they are extended by exchangables which contain a coarray...